[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "3499977893", # Advanced Developer Tools's Workshop ID
    "1638341685" # DUI Workshop ID
]

[csa38]
extends = "default"
workshop = [
    "641305739", # CSA38's Workshop ID
]

[rhs]
extends = "default"
workshop = [
    "843577117", # RHSUSAF's Workshop ID
    "843425103", # RHSAFRF's Workshop ID
    "843593391", # RHSGREF's Workshop ID
    "843632231" # RHSSAF's Workshop ID
]

[fow]
extends = "default"
workshop = [
    "891433622", # FOW's Workshop ID
]

[usp]
extends = "default"
workshop = [
    "1795825073", # USP AIO Workshop ID
    "2056229605", # USP Gear - ACE Workshop ID
]
